### ISSUE TITLE
Seems to depend on 'sarge'

### ISSUE THREAD

**Issue by phaza** [adamcharnock/dokku-client#1]
Seems like you've left out adding sarge as an installation dependency.

```
Traceback (most recent call last):
  File "/usr/local/bin/dokku-client", line 9, in <module>
    load_entry_point('dokku-client==0.2.2', 'console_scripts', 'dokku-client')()
  File "/usr/local/lib/python2.7/site-packages/dokku_client/client.py", line 26, in main
    commands = load_commands()
  File "/usr/local/lib/python2.7/site-packages/dokku_client/command_tools.py", line 8, in load_commands
    command_class = entry_point.load()
  File "build/bdist.macosx-10.8-x86_64/egg/pkg_resources.py", line 2108, in load
  File "/usr/local/lib/python2.7/site-packages/dokku_client/commands/__init__.py", line 3, in <module>
    from sarge import capture_stdout, run
ImportError: No module named sarge
```

I installed sarge via pip, and then everything worked smoothly.
I know very little python, but I assume you can add sarge as an installation dependency somewhere.

**Comment by sherzberg** [comment]
Looks like a release to pypi is needed. The dependency is added to setup.py

**Comment by chriskilding** [comment]
+1 for pushing an update to pypi please :)

**Comment by adamcharnock** [comment]
Wow, I'm sure late replying to this one. Version 0.2.3 released.
