### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dxokal** [adamcharnock/dokku-client#3]
I got error when :

```
dokku-client help        
Traceback (most recent call last):
  File "/usr/bin/dokku-client", line 9, in <module>
    load_entry_point('dokku-client==0.2.3', 'console_scripts', 'dokku-client')()
  File "/usr/lib/python3.5/site-packages/dokku_client/client.py", line 26, in main
    commands = load_commands()
  File "/usr/lib/python3.5/site-packages/dokku_client/command_tools.py", line 8, in load_commands
    command_class = entry_point.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/dokku_client/commands/prompt.py", line 18
    print "Running command: %s" % ' '.join(call_args)

```

How can I do ?

**Comment by adamcharnock** [comment]
This code isn't python 3 compatible unfortunately. Using python 2 should fix this.

I haven't touched this project in a while, so I'm not honestly sure how functional it is right now.

**Comment by dxokal** [comment]
ok
